name: quran_sdk
description: Offline-first Quran SDK for Flutter with Arabic and English translations, audio support, search functionality, pages, sajda verses, and hizb.
version: 0.1.7
homepage: https://github.com/wpdynamo/quran_sdk
repository: https://github.com/wpdynamo/quran_sdk
issue_tracker: https://github.com/wpdynamo/quran_sdk/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/data/surahs.json
    - assets/data/verses.json
    - assets/data/juz.json
    - assets/data/pages.json
    - assets/data/sajda.json
    - assets/data/hizb.json
